CREATE TABLE DEPT
    (DEPTNO INTEGER PRIMARY KEY,
    DNAME VARCHAR(18) NOT NULL,
    HEAD CHAR(10) NOT NULL);
CREATE UNIQUE INDEX DEPTNOINDEX ON DEPT(DEPTNO);

CREATE TABLE STU
    (STNO CHAR(10) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    AGE INTEGER NOT NULL,
    MONIT CHAR(10) NOT NULL,
    MACR INTEGER NOT NULL,
    MICR INTEGER,
    EDATE DATETIME NOT NULL,
    DEPTNO INTEGER NOT NULL);
CREATE UNIQUE INDEX STNOINDEX ON STU(STNO);

CREATE TABLE TEACHER
    (TNO CHAR(10) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    AGE INTEGER NOT NULL,
    WDATE DATETIME NOT NULL,
    DEPTNO INTEGER NOT NULL);
CREATE UNIQUE INDEX TNOINDEX ON TEACHER(TNO);
