SELECT NAME,DNAME
FROM TEACHER X,DEPT
WHERE X.DEPTNO=DEPT.DEPTNO AND
    X.WDATE<(SELECT WDATE
            FROM TEACHER Y
            WHERE Y.TNO=(SELECT HEAD
                    FROM DEPT
                    WHERE DEPTNO=X.DEPTNO));
